greenery:

  outputs:
    dbt_zkan:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: dbt_zkan

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: prod

    dbt_valen_bigquery:
      type: bigquery
      method: service-account
      project: gentle-mapper-384408
      dataset: dbt_valen
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/gentle-mapper-384408-798d770d1940-bigquery.json
      location: asia-southeast1

    prod_bigquery:
      type: bigquery
      method: service-account
      project: gentle-mapper-384408
      dataset: deb_bootcamp
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/YOUR-KEYFILE.json
      location: asia-southeast1

  target: dbt_valen_bigquery